import argparse
import csv
import json
import re
from pathlib import Path


VALID_SMELLS = {"GC", "UD", "IM", "HM"}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse agent JSON outputs and generate a CSV file."
    )

    parser.add_argument(
        "--input-dir",
        default="data/outputs/agent_outputs",
        help="Directory containing JSON files generated by the agent.",
    )

    parser.add_argument(
        "--output",
        default="data/outputs/parsed_agent_outputs.csv",
        help="Path to the output CSV file.",
    )

    return parser.parse_args()


def infer_smell_from_filename(json_path: Path) -> str:
    filename = json_path.name.upper()

    # Matches patterns such as:
    # 0001_HM_xxx.json
    # 20260529_HM_xxx_verdict.json
    # HM_xxx.json
    # xxx_IM_xxx.json
    matches = re.findall(r"(?:^|[_\-.])(GC|UD|IM|HM)(?:[_\-.]|$)", filename)

    if not matches:
        raise ValueError(f"Could not infer smell from filename: {json_path.name}")

    if len(set(matches)) > 1:
        raise ValueError(
            f"Ambiguous smell in filename {json_path.name}: {sorted(set(matches))}"
        )

    return matches[0]


def normalize_detection(value):
    if isinstance(value, bool):
        return 1 if value else 0

    if isinstance(value, str):
        value_lower = value.strip().lower()

        if value_lower == "true":
            return 1

        if value_lower == "false":
            return 0

        if value_lower == "1":
            return 1

        if value_lower == "0":
            return 0

    if isinstance(value, int) and value in {0, 1}:
        return value

    raise ValueError(f"Invalid detection value: {value}")


def read_json_file(json_path: Path) -> dict:
    with json_path.open("r", encoding="utf-8") as file:
        return json.load(file)


def parse_result(json_path: Path) -> dict:
    data = read_json_file(json_path)
    smell = infer_smell_from_filename(json_path)

    required_fields = {"target", "detection", "justification"}
    missing_fields = required_fields - set(data.keys())

    if missing_fields:
        raise ValueError(
            f"File {json_path} is missing fields: {sorted(missing_fields)}"
        )

    return {
        "smell": smell,
        "target": data["target"],
        "detection": normalize_detection(data["detection"]),
        "justification": data["justification"],
    }


def main():
    args = parse_args()

    input_dir = Path(args.input_dir)
    output_path = Path(args.output)

    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory not found: {input_dir}")

    json_files = sorted(input_dir.glob("*.json"))

    if not json_files:
        raise FileNotFoundError(f"No JSON files found in: {input_dir}")

    rows = []
    failures = []

    for json_path in json_files:
        try:
            row = parse_result(json_path)
            rows.append(row)
        except Exception as exc:
            failures.append(
                {
                    "file": str(json_path),
                    "error": str(exc),
                }
            )

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=["smell", "target", "detection", "justification"],
        )

        writer.writeheader()
        writer.writerows(rows)

    print(f"[OK] Parsed JSON files: {len(rows)}")
    print(f"[OK] Output CSV: {output_path}")

    if failures:
        print(f"[WARN] Failed files: {len(failures)}")
        for failure in failures[:30]:
            print(f"- {failure['file']}: {failure['error']}")

        if len(failures) > 30:
            print(f"... and {len(failures) - 30} more failures.")

    return 0 if not failures else 1


if __name__ == "__main__":
    raise SystemExit(main())